parameters:
    nfq_banner.searchable_fields: [id, title, link, text]

services:
    nfq_banner.generic_search:
        class: Nfq\BannerBundle\Service\Admin\Search\BannerSearch
        arguments: [%nfq_banner.searchable_fields%]
        tags:
          - { name: nfq_admin.search, manager: nfq_banner.admin.banner_manager }

    nfq_banner.admin.banner_manager:
        class: Nfq\BannerBundle\Service\Admin\BannerManager
        arguments: ["@nfq_banner.repository.banner"]
        tags:
          - { name: nfq_admin.manager }

    nfq_banner.banner_manager:
        class: Nfq\BannerBundle\Service\BannerManager
        arguments:
            ["@nfq_banner.repository.banner", "@nfq_banner.admin.service.banner_upload_manager", %nfq_banner%]

    nfq_banner.admin.service.banner_upload_manager:
        class: Nfq\BannerBundle\Service\Admin\BannerUploadManager
        arguments: ["%nfq_banner.config%"]

    #Repositories
    nfq_banner.repository.banner:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Nfq\BannerBundle\Entity\Banner

    #Listeners
    nfq_banner.notice_listener:
        class: Nfq\AdminBundle\EventListener\NoticeListener
        arguments: ["@nfq_admin.notice_service"]
        tags:
            - { name: kernel.event_listener, event: banner.after_save, method: onMessage, priority: -10 }
            - { name: kernel.event_listener, event: banner.after_insert, method: onMessage, priority: -10 }
            - { name: kernel.event_listener, event: banner.after_delete, method: onMessage, priority: -10 }

    nfq_banner.entity_listener.file_upload:
        class: Nfq\BannerBundle\EventListener\Doctrine\FileUploadListener
        arguments: ["@nfq_banner.admin.service.banner_upload_manager"]
        tags:
            - { name: doctrine.orm.entity_listener, entity: Nfq\BannerBundle\Entity\Banner, event: postPersist, priority: 15 }
            - { name: doctrine.orm.entity_listener, entity: Nfq\BannerBundle\Entity\Banner, event: postUpdate, priority: 15 }
            - { name: doctrine.orm.entity_listener, entity: Nfq\BannerBundle\Entity\Banner, event: preRemove, priority: 15 }
            - { name: doctrine.orm.entity_listener, entity: Nfq\BannerBundle\Entity\Banner, event: postRemove, priority: 15 }
            - { name: doctrine.orm.entity_listener, entity: Nfq\BannerBundle\Entity\Banner, event: preFlush, priority: 15 }

    #Admin menu listener
    nfq_banner.admin_configure_menu_listener:
        parent: nfq_admin.menu.base_listener
        class: Nfq\BannerBundle\EventListener\AdminMenuListener
        tags:
          - { name: kernel.event_listener, event: nfq_admin.side_menu_configure, method: onMenuConfigure }

    #Twig extensions
    nfq_banner.twig.banner_extension:
        class: Nfq\BannerBundle\Twig\BannerExtension
        arguments: ["@nfq_banner.banner_manager"]
        tags:
            - { name: twig.extension }

    #Validators
    validator.exact_image_dimensions:
        class: Nfq\BannerBundle\Validator\Constraint\BannerDimensionsValidator
        arguments: [ "@nfq_banner.banner_manager" ]
        tags:
            - { name: validator.constraint_validator, alias: nfq_banner_dimmensions_validator }
